// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4aw8o273JbhYkf9asUGoXWMO3ZonlPFU',
    appId: '1:837461181268:web:f182387ad29f71be8dfec1',
    messagingSenderId: '837461181268',
    projectId: 'memolette-3a68b',
    authDomain: 'memolette-3a68b.firebaseapp.com',
    storageBucket: 'memolette-3a68b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz5g_tdV_CNVNYFC5KM5X-1m2qMtVHuLo',
    appId: '1:837461181268:android:7be5fad2919bfa918dfec1',
    messagingSenderId: '837461181268',
    projectId: 'memolette-3a68b',
    storageBucket: 'memolette-3a68b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZn2PBg3U9jOgptWVCcBhzbSHC5FOU96M',
    appId: '1:837461181268:ios:e994795ef029d5238dfec1',
    messagingSenderId: '837461181268',
    projectId: 'memolette-3a68b',
    storageBucket: 'memolette-3a68b.firebasestorage.app',
    iosBundleId: 'com.memolette.memolette',
  );
}
